require('core.plugin')
require('core.options')
require('core.keymaps')
require('core.colorscheme')
require('plugins.nvim-cmp')
require('plugins.bufferline')
require('plugins.lsp.mason')
require('plugins.lsp.lspconfig')
